"""MadLib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLaoLRybOetKqqHdLQOJ6h-zVxpfl2W_

MadLib Project: Create your own contry
"""

#Welcome to the MadLib
print("Welcome, governor! I hope you are ready to tell us more about your country!")

#Ask for user's name
your_name = input("Enter your name:\n")

#Comment on user's name length
if len(your_name) > 6:
  print("What a long name!")
else:
  print("What a short name!")

#Instructions for the user
print("Please enter your response to the following prompts: ")

#Variables to be assigned after the user's input.
country_name = input("Create a name for a fake country:\n")
birthday = int(input("Enter the year you were born (Example: 1990):\n"))
adjetive = input("Enter an adjetive that describes you as a person:\n")
rule = input("Enter a rule you think is important to live by:\n")
second_rule = input("Enter a second rule you think is important to live by:\n")
punishment = input("Enter a punishment that you would consider harsh, but reasonable:\n")
hobby = input("Enter a hobby that you enjoy:\n")
hobby2 = input("Enter a second hobby that you enjoy:\n")
hate = input("Enter something that you absolutely hate to do:\n")
fav_music = input("Enter your favorite type of music:\n")
fav_food = input("Enter your favorite food:\n")
fav_food2 = input("Enter your second favorite food:\n")
fav_drink = input("Enter your favorite drink:\n")
clothing = input("Enter a typical clothing or special uniform you might wear:\n")
landform = input("Enter your favorite landform or type of outdoor environment:\n")
water_landform = input("Enter your favorite type of waer landform or environment:\n")
fav_color = input("Enter your favorite color:\n")
impt_object = input("Enter an important object in your life:\n")
quote = input("Last One! Enter your favorite quote or words of wisdom:\n")

#Mark the beginning of the story
print("*********************************************************")

#MadLib story title
print("Welcome to " + country_name + "!")

#Phrases for the MadLib, completed with the variables from above. The user input will change the message.
print(f'''In the land of {country_name}, which was founded on {str(birthday)}, things are a little different than what you may be accustomed to.
First of all, you should understand that the government is run by a(n) {adjetive} person named {your_name}.
They insist that {rule} and {second_rule}.
You should always make sure to abide by these laws to avoid {punishment} as punishment.
The culture of {country_name} is interesting as well.
Citizens mostly enjoy {hobby} and {hobby2} in their spare time, and by the order of {your_name}, {hate} has been outlawed due to lack of interest.
Citizens also love listening to {fav_music} music more than any other kind.
The citizens are very particular about their diets as well, only eating {fav_food} and {fav_food2} and drinking {fav_drink}.
Finally, they can be seen wearing {clothing} on a daily basis.
Geographically speaking, the land is mostly covered with {landform} with a(n) {water_landform} nearby.
The {fav_color} national flag can be seen flying above the capitol building, with the national emblem of a {impt_object} showcased in the center of the fabric.
When visiting {country_name}, just remember the country's motto "{quote}".''')

#Mark the end of the story
print("*********************************************************")

#Farewell to user, wishing the best in governing their fake country
print("Best of luck in governing " + country_name + ", " + your_name + "!")

#This MadLib was inspired by:
print("MadLib adapted from: https://www.teacherspayteachers.com/Product/Back-to-School-Crazy-Country-Mad-Lib-Pack-1357990")

#Show output to user in case they're using CMD console (if not, it would automatically close after and not show the story)
input()
